In [ ]:
pip install numpy



Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [8]:
#creating numPy 
import numpy as np

array=np.array([10,5,15,20])
print("Element of array:",array)

Element of array: [10  5 15 20]


In [10]:
# array operating :lets find average of above array elements
average = np.mean(array)
print("average is :" ,average)

average of : 12.5


In [12]:
#multi dimension Array
height_cm=np.array([[100,111,100],[110,105,125],[120,115,130]])
print("height of 2022 d batch student:\n",height_cm)

height of 2022 d batch student:
 [[100 111 100]
 [110 105 125]
 [120 115 130]]


In [16]:
#array indexing and slicing
first_bench_std_height=height_cm[0]
print("fbsh",first_bench_std_height)

bata_height=height_cm[1][2]
print("rangit bata height is ",bata_height)

last_height=height_cm[:-1]
print("last bench height is ",last_height)

fbsh [100 111 100]
rangit bata height is  125
last bench height is  [[100 111 100]
 [110 105 125]]


In [19]:
#kets convert temperate from c to f and c to k
temp=np.array([[20,25,29],[19,23,22],[18,20,37]])
f=(temp * 9/5)+32
print(" temp in F is :",f)


k=(temp +273.15)
print("temp in kelvin is :",k)

 temp in F is : [[68.  77.  84.2]
 [66.2 73.4 71.6]
 [64.4 68.  98.6]]
temp in kelvin is : [[293.15 298.15 302.15]
 [292.15 296.15 295.15]
 [291.15 293.15 310.15]]


In [93]:
# linear algebra
sales=np.array([[500,100,200],[750,1000,1500]])
quantity=np.array([[10,20,30],[100,200,50]])
revenue=np.dot(sales,quantity.T)

In [32]:
#zeros and onnes (matrix)
print("zeros matrix 3x3:\n",np.zeros((3,3),dtype=int))
print("ones matrix 3x3:\n",np.ones((3,3),dtype=int))
print("\nEye matrix 5x5:\n",np.eye((5),dtype=int))




zeros matrix 3x3:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
ones matrix 3x3:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Eye matrix 5x5:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [97]:
#create 1D numPy array values ranging from 0 to 9
array_1D=np.arange(10)
print("1D:",array_1D)

#creare a 2D NUMPY array with the shape(3,3) containg values frpm 1to 10
array_2D=np.arange(1,10).reshape(3,3)
print("\n2D:\n",array_2D)


1D: [0 1 2 3 4 5 6 7 8 9]

2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
#perform element-wise addition,suntration,multiplication,and devision on 1D array [1,2,3] and [4,5,6]
array1=np.array([1,2,3])
array2=np.array([4,5,6])

addition=array1 + array2
subtraction=array1 - array2
multiplication=array1 * array2
devision=array2 / array1

print(addition,subtraction,multiplication,devision)





[5 7 9] [-3 -3 -3] [ 4 10 18] [4.  2.5 2. ]
